<?php return array(
'right'=>'chat.setting,chat.moderate',
'menu'=>10,
'widget'=>'chat',
'file'=>array(
	'admin/controller/chat.php',
	'admin/model/chat.php',
	'config/chat.php',
	'config/chat-blacklist.php',
	'controller/chat.php',
	'data/chat/',
	'model/chat.php',
	'public/css/chat.css',
	'public/chat-smile/',
	'public/js/jquery.chat.js',
	'public/smile.png',
	'view/chatIndex.php',
	'view/widgetChat.php',
	'view/widgetChatForm.php',
	'widget/chat.php',
	'widget/chatForm.php'
)
);