<?php return array(
'right'=>'chat.setting,chat.moderate',
'menu'=>10,
'widget'=>'chat',
'file'=>array(
	'admin/controller/chat.php',
	'config/chat.php',
	'config/chat-blacklist.php',
	'controller/chat.php',
	'data/chat.txt',
	'model/chat.php',
	'public/css/chat.css',
	'public/chat-smile/',
	'public/js/jquery.chat.js',
	'view/chatIndex.php',
	'view/widgetChat.php',
	'widget/chat.php'
)
);