<?php return array(
'right'=>'demotivator.setting,demotivator.moderate',
'widget'=>'demotivatorLast',
'menu'=>'8,9',
'table'=>'demotivator',
'file'=>array(
	'admin/controller/DemotivatorController.php',
	'config/demotivator.php',
	'controller/DemotivatorController.php',
	'data/arial.ttf',
	'public/demotivator/',
	'public/css/demotivator.css',
	'view/demotivatorConstruct2.php',
	'view/demotivatorIndex.php',
	'view/demotivatorRename.php',
	'view/demotivatorSuccess.php',
	'widget/DemotivatorLastWidget.php',
)
);