<?php return array(
'right'=>'form.*',
'widget'=>'form',
'menu'=>'7',
'table'=>'frm_form(title),frm_field',
'file'=>array(
	'admin/controller/form.php',
	'admin/hook/languageCreate.form.php',
	'admin/hook/menuItemDelete.form.php',
	'admin/hook/widgetDelete.form.php',
	'admin/model/form.php',
	'admin/model/frmField',
	'admin/public/icon/field16.png',
	'admin/public/icon/field32.png',
	'admin/view/formField.php',
	'admin/view/formForm.php',
	'controller/form.php',
	'model/form.php',
	'view/formSuccess.php',
	'widget/form.php'
)
);