<?php return array(
'debug'=>true,
'adminEmailEmail'=>'admin@example.com',
'adminEmailName'=>'CMS',
'dbDriver'=>'mysql',
'mysqlHost'=>'localhost',
'mysqlUser'=>'root',
'mysqlPassword'=>'',
'mysqlDatabase'=>'cms',
'mainPath'=>'article/view/index',
'link'=>array(
'article/view/about'=>'about',
'article/blog/news'=>'news',
'catalog/1'=>'catalog',
'form/1000'=>'contact',
'article/list/article'=>'articles'
),
'template'=>array(
'article/blog/news'=>'red'
),
'languageDefault'=>'ru',
'languageList'=>array(
'ru',
'en'
)
);